# Automatically generated by Pynguin.
import solution_copy as module_0


def test_case_0():
    try:
        dict_0 = {}
        var_0 = module_0.solution(dict_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = True
        list_0 = [bool_0, bool_0]
        dict_0 = None
        tuple_0 = list_0, dict_0
        var_0 = module_0.solution(tuple_0)
        assert var_0 == 3
        assert module_0.PYNGUIN_DANGER_AWARE is True
        int_0 = -109
        var_1 = module_0.shortest_path(tuple_0, bool_0, list_0, int_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bool_0 = False
        int_0 = 1603
        str_0 = '3#`'
        int_1 = 5152
        dict_0 = {bool_0: int_0, str_0: int_1, int_1: int_1}
        var_0 = module_0.shortest_path(bool_0, int_0, dict_0, bool_0)
    except BaseException:
        pass

test_case_0()

test_case_1()

test_case_2()